FROM maven:3.9.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean install -DskipTests

FROM openjdk:21-jdk-slim
LABEL authors="Antony & Wallyson"

#ARG JAR_FILE=target/*.jar
#COPY ${JAR_FILE} app.jar
COPY --from=build /app/target/*.jar app.jar

WORKDIR /app

ENTRYPOINT ["java","-jar","/app.jar"]